version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: commerce-postgres
    environment:
      POSTGRES_DB: commerce_lab
      POSTGRES_USER: lab_user
      POSTGRES_PASSWORD: lab_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lab_user -d commerce_lab"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: commerce-redis
    ports:
      - "6379:6379"

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.4
    container_name: commerce-redpanda
    command:
      - redpanda start
      - --smp 1
      - --memory 512M
      - --overprovisioned
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"

  jaeger:
    image: jaegertracing/all-in-one:1.54
    container_name: commerce-jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    container_name: commerce-api
    environment:
      DATABASE_URL: postgresql+asyncpg://lab_user:lab_password@postgres:5432/commerce_lab
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      JWT_SECRET_KEY: super-secret-enterprise-agent-lab-jwt-token-key-32chars
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      context: ../apps/web
      dockerfile: Dockerfile
    container_name: commerce-web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  pgdata:
